[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = ["npm install", "cd client && npm install"]

[phases.build]
cmds = ["cd client && npm run build"]
# cache-bust: 2026-05-15d

[start]
cmd = "node server.js"
